backend:
  image: cosmin12300/backend:latest
  replicas: 1
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image: cosmin12300/frontend:latest
  replicas: 1
  service:
    type: LoadBalancer
  resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

mysql:
  image: mysql:lts
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storage: 5Gi
  secret:
    rootPassword: password