backend:
  image: cosmin12300/backend:latest
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image: cosmin12300/frontend:latest
  replicas: 1
  resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

mysql:
  image: mysql:lts
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storage: 5Gi
    storageClass: standard
  secret:
    rootPassword: password

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend-service
            port: 80
    - host: backend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: backend-service
            port: 3000
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: prometheus-kube-prometheus-prometheus
            port: 9090
    - host: grafana.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: prometheus-grafana
            port: 80
    - host: argocd.local
      namespace: argocd
      paths:
        - path: /
          pathType: Prefix
          service:
            name: argocd-server
            port: 80