apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-application.name" . }}-backend-deployment
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-application.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "my-application.name" . }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "my-application.name" . }}-mysql-secret
              key: rootPassword
        - name: MYSQL_URL
          value: {{ include "my-application.name" . }}-mysql