apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: {{ include "my-application.name" . }}-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000