apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: {{ include "my-application.name" . }}-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80