apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/kube-prometheus
    targetRevision: release-0.71
    path: manifests/setup
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false  # Never auto-delete CRDs!
      selfHeal: true
    syncOptions:
    - Validate=false  # Skip validation for large CRDs
    - ServerSideApply=true