apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressnginx
  namespace: argocd
spec:
  destination:
    namespace: ingressnginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      valueFiles:
      - values.yaml
      values: |
        controller:
          replicaCount: 1
          
          metrics:
            enabled: true  # Required for Prometheus scraping
          
          # Disable HTTPS features
          containerPort:
            https: null
          service:
            https:
              enabled: false
            targetPorts:
              https: null
          
          # Configuration
          config:
            ssl-redirect: "false"
          
          # Disable admission webhooks
          admissionWebhooks:
            enabled: false
        
        # No TLS certificates
        tls: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true