apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-application.name" . }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ include "my-application.name" . }}-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "my-application.name" . }}-mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "my-application.name" . }}-mysql-secret
              key: rootPassword
        ports:
        - containerPort: 3306
          name: mysql
          {{ if .Values.mysql.persistence.enabled }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          {{ end }}
          {{ if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mysql.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mysql.persistence.storage }}
          {{ end }}