backend:
  image: cosmin12300/backend:9e549998b779aed9e0a3bc98b25868a7e17ec5ef
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image: cosmin12300/frontend:c97cded43732f6626a776adcf265887ef68a04c1
  replicas: 1
  resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

mysql:
  image: mysql:lts
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storage: 5Gi
    storageClass: gp2
  secret:
    rootPassword: password

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend-service
            port: 80
    - host: backend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: backend-service
            port: 3000