prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'ingress-controller'
      scrape_interval: 30s
      metrics_path: /metrics
      static_configs:
        - targets:
            - nginx-ingress-ingress-nginx-controller-metrics:10254