apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressnginx
  namespace: argocd
spec:
  destination:
    namespace: ingressnginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer  # Expose the ingress controller via a LoadBalancer
          ingressClassResource:
            name: nginx
            enabled: true
          ingressClass: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true