apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.2.1
    helm:
      parameters:
      - name: crds.enabled
        value: "true"
      valueFiles:
      - values.yaml
      values: |
        prometheus:
          enabled: true 
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /
            hosts:
              - prometheus.local
            paths:
              - /
          prometheusSpec:
            storageSpec:  # ← Required for persistence
              volumeClaimTemplate:
                spec:
                  storageClassName: standard
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
            resources:  # ← Prevent OOM
              requests:
                memory: 1Gi
                cpu: 500m
            additionalScrapeConfigs:
              - job_name: 'ingress-controller'
                scrape_interval: 30s
                metrics_path: /metrics
                static_configs:
                  - targets:
                    - ingressnginx-ingress-nginx-controller-metrics.ingressnginx.svc.cluster.local:10254
        
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /
            hosts:
              - grafana.local
            paths:
              - /
        
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - alertmanager.local
            annotations:
              kubernetes.io/ingress.class: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true