name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker image
        run: docker build -t cosmin12300/backend:latest -t cosmin12300/backend:${{ github.sha }} ./Backend

      - name: Push Backend Docker image
        run: |
          docker push cosmin12300/backend:latest
          docker push cosmin12300/backend:${{ github.sha }}
