name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/web-app:latest -t your-dockerhub-username/web-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/web-app:latest
          docker push your-dockerhub-username/web-app:${{ github.sha }}
