name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'myapplication/Frontend/**'
      
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker image
        run: docker build -t cosmin12300/frontend:latest -t cosmin12300/frontend:${{ github.sha }} ./myapplication/Frontend

      - name: Push Frontend Docker image
        run: |
          docker push cosmin12300/frontend:latest
          docker push cosmin12300/frontend:${{ github.sha }}

      - name: Update Helm values.yaml with new Docker tag
        run: |
          # Debug information
          echo "Current directory: $(pwd)"
          echo "Checking if values.yaml exists:"
          ls -la myapplication/chart/values.yaml
          
          # Update the image tag in values.yaml
          sed -i "s|cosmin12300/frontend:.*|cosmin12300/frontend:${{ github.sha }}|" myapplication/chart/values.yaml
          
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit and push changes
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout master
          
          # Verify git status
          git status
          
          # Add all modified files
          git add .
          
          # Verify the file was added
          git status
          
          git commit -m "Update frontend image tag to ${{ github.sha }} [skip ci]"
          git push origin master